/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDINVENTARIOS.VISTAS;

import MD.GENERALES.VISTAS.interfazPrincipal;
import MDINVENTARIOS.CONTROLADORES.BDDInventarios;
import MDINVENTARIOS.MODELOS.Clasificacion;
import javax.swing.JOptionPane;

/**
 *
 * @author brula
 */
public class detallesClasificacion extends javax.swing.JFrame {
    private int id;

    /**
     * Creates new form detallesClasificacion
     */
    public detallesClasificacion(String folio, String nombre) {
        initComponents();
        Clasificacion cla = BDDInventarios.selectClasificacionFiltrada(folio, nombre);
        
        id = cla.getId_clas();
        this.txtFolio.setText(cla.getFol_clas());
        this.txtNombre.setText(cla.getNom_clas());
        this.chekGenera.setSelected(cla.getStock_clas());
        
        desbloquearDatos(false);
    }
    
    private void desbloquearDatos(boolean valor){
        this.txtFolio.setEditable(valor);
        this.txtNombre.setEditable(valor);
        this.chekGenera.setEnabled(valor);
        this.btnEditar.setEnabled(valor);
        this.btnEliminar.setEnabled(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        chekGenera = new javax.swing.JCheckBox();
        btnEditar = new javax.swing.JButton();
        brnSalir = new javax.swing.JButton();
        btnDesbloquearDatos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Clasificacion:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        jLabel1.setText("Folio:");

        jLabel2.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        chekGenera.setText("¿Genera stock?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chekGenera)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFolio)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chekGenera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEditar.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        brnSalir.setBackground(new java.awt.Color(255, 255, 204));
        brnSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        brnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/salir.png"))); // NOI18N
        brnSalir.setText("Salir");
        brnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brnSalirMouseClicked(evt);
            }
        });

        btnDesbloquearDatos.setBackground(new java.awt.Color(255, 255, 204));
        btnDesbloquearDatos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDesbloquearDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/desbloquear.png"))); // NOI18N
        btnDesbloquearDatos.setText("Desbloquear Datos");
        btnDesbloquearDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearDatosMouseClicked(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 204));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brnSalir)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesbloquearDatos)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnSalir)
                    .addComponent(btnEditar)
                    .addComponent(btnDesbloquearDatos)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
       MDINVENTARIOS.CONTROLADORES.MDINVENTARIOS nuevaClasificacion = new MDINVENTARIOS.CONTROLADORES.MDINVENTARIOS();
       Clasificacion clasificacion = new Clasificacion(id,txtFolio.getText(),txtNombre.getText(),chekGenera.isSelected());
       String respuesta = nuevaClasificacion.modificarClasificacion(clasificacion);
       if(respuesta.equals("Clasificación modificada con éxito.")){
           javax.swing.JOptionPane.showMessageDialog(this, "Clasificación modificada con éxito.");
       }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void brnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnSalirMouseClicked
        AgregarClasificacion.isAbiertoDetallesClasificacion = false;
        dispose();
    }//GEN-LAST:event_brnSalirMouseClicked

    private void btnDesbloquearDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearDatosMouseClicked
        desbloquearDatos(true);
        javax.swing.JOptionPane.showMessageDialog(this, "Ahora ya puede trabajar con los datos.\n NOTA: Cualquier cambio hecho después de presionar Editar, no se podrá recuperar.");
    }//GEN-LAST:event_btnDesbloquearDatosMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere eliminar esta clasificación"+"\n"+"ALERTA:", "ELIMINAR CLASIFICACION", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
       
            if(BDDInventarios.deleteClasificacion(id)){
                javax.swing.JOptionPane.showMessageDialog(this, "Clasificación eliminada con éxito.");
                AgregarClasificacion.isAbiertoDetallesClasificacion = false;
                dispose();
                return;
            }
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar la clasificación.");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnSalir;
    private javax.swing.JButton btnDesbloquearDatos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JCheckBox chekGenera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
