/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDINVENTARIOS.VISTAS;

import MDINVENTARIOS.CONTROLADORES.BDDInventarios;
import MDINVENTARIOS.MODELOS.Movimiento;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import static javax.swing.JOptionPane.showConfirmDialog;

/**
 *
 * @author brula
 */
public class detallesAsignacion extends javax.swing.JFrame {
    private int id;

    /**
     * Creates new form detallesAsignacion
     * @param id
     */
    public detallesAsignacion(int id) {
        initComponents();
        
        this.id = id;
        
        Movimiento movimiento = BDDInventarios.selectMovimientoFiltrado(id);
        
        this.txtFecha.setText(movimiento.getFec_mov());
        this.txtPersona.setText(BDDInventarios.selectNombrePersonaMovimiento(movimiento.getId_per()));
        this.checkStatus.setSelected(movimiento.getSta_mov());
        this.txtObservaciones.setText(movimiento.getObs_mov());
        
        llenarLista(BDDInventarios.selectProductosAsignadosMovimiento(id));
        
        desbloquearDatosLista(false);
        desbloquearDatosFormulario(false);
        
        
    }
    
    public void llenarLista(ArrayList<String> arrayProductos){
        DefaultListModel modelo = new DefaultListModel();
       
        for(int i = 0; i < arrayProductos.size(); i++){
            modelo.addElement(arrayProductos.get(i));
        }
        
        this.listaProductos.setModel(modelo);
    }//llenarLista}
    
    
    public void desbloquearDatosLista(boolean valor){
        this.listaProductos.setEnabled(valor);
        this.btnEditarCantidad.setEnabled(valor);
        this.btnQuitarListta.setEnabled(valor);
    }//desbloquearDatosLista
    
    public void desbloquearDatosFormulario(boolean valor){
        this.txtFecha.setEnabled(false);
        this.txtPersona.setEnabled(false);
        this.checkStatus.setEnabled(valor);
        this.txtObservaciones.setEditable(valor);
        this.btnEditar.setEnabled(valor);
    }//desbloquearDatosLista

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtPersona = new javax.swing.JTextField();
        btnDesbloquearDatos = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        checkStatus = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        btnQuitarListta = new javax.swing.JButton();
        btnEditarCantidad = new javax.swing.JButton();
        btnDesbloquearDatosLista = new javax.swing.JButton();
        btnEliminarMovimiento = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos movimiento:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setText("Fecha del movimiento: ");

        jLabel3.setText("Observaciones:");

        jLabel5.setText("Persona involucrada:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        btnDesbloquearDatos.setBackground(new java.awt.Color(255, 255, 204));
        btnDesbloquearDatos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDesbloquearDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/desbloquear.png"))); // NOI18N
        btnDesbloquearDatos.setText("Desbloquear datos");
        btnDesbloquearDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesbloquearDatosMouseEntered(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        checkStatus.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDesbloquearDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(checkStatus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesbloquearDatos)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos asignados:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaProductos);

        btnQuitarListta.setBackground(new java.awt.Color(255, 255, 204));
        btnQuitarListta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuitarListta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/quitar.png"))); // NOI18N
        btnQuitarListta.setText("Quitar");
        btnQuitarListta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitarListtaMouseClicked(evt);
            }
        });

        btnEditarCantidad.setBackground(new java.awt.Color(255, 255, 204));
        btnEditarCantidad.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEditarCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/editar.png"))); // NOI18N
        btnEditarCantidad.setText("Editar Cantidad");
        btnEditarCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCantidadMouseClicked(evt);
            }
        });

        btnDesbloquearDatosLista.setBackground(new java.awt.Color(255, 255, 204));
        btnDesbloquearDatosLista.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDesbloquearDatosLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/desbloquear.png"))); // NOI18N
        btnDesbloquearDatosLista.setText("Desbloquear datos");
        btnDesbloquearDatosLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearDatosListaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDesbloquearDatosLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitarListta)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCantidad)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesbloquearDatosLista)
                    .addComponent(btnQuitarListta)
                    .addComponent(btnEditarCantidad))
                .addContainerGap())
        );

        btnEliminarMovimiento.setBackground(new java.awt.Color(255, 255, 204));
        btnEliminarMovimiento.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEliminarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/eliminar.png"))); // NOI18N
        btnEliminarMovimiento.setText("Eliminar movimiento");
        btnEliminarMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMovimientoMouseClicked(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/salir.png"))); // NOI18N
        jButton7.setText("Salir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarMovimiento)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarMovimiento)
                            .addComponent(jButton7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        ventanaMovimientos.isAbiertodetallesAsignacion = false;
        dispose();
    }//GEN-LAST:event_jButton7MouseClicked

    private void btnQuitarListtaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarListtaMouseClicked
        try {
            DefaultListModel modeloLista = (DefaultListModel)listaProductos.getModel();
            int index =  this.listaProductos.getSelectedIndex();
            String datos = (String) modeloLista.getElementAt(index);

            String[] temp = datos.split("/");
            String nombre = temp[0];
            String marca = temp[1];
            String modelo = temp[2];
            int idProducto = BDDInventarios.buscarIdProducto(nombre, marca, modelo);
            int cantidad = Integer.parseInt(temp[3]);
            
            boolean respuesta = BDDInventarios.deleteProductoAsignado(id, idProducto);          
            
            if(respuesta){
                javax.swing.JOptionPane.showMessageDialog(this, "Producto quitado con éxito.");
                llenarLista(BDDInventarios.selectProductosAsignadosMovimiento(id));
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo quitar el producto.");
            }
        }catch(Exception ee){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto.");
        }
    }//GEN-LAST:event_btnQuitarListtaMouseClicked

    private void btnEditarCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCantidadMouseClicked
        try {
            DefaultListModel modeloLista = (DefaultListModel)listaProductos.getModel();
            int index =  this.listaProductos.getSelectedIndex();
            String datos = (String) modeloLista.getElementAt(index);

            String[] temp = datos.split("/");
            String nombre = temp[0];
            String marca = temp[1];
            String modelo = temp[2];
            int id_pro = BDDInventarios.buscarIdProducto(nombre, marca, modelo);
            int cantidad;
                    try{
                        cantidad = Integer.parseInt(javax.swing.JOptionPane.showInputDialog("¿Qué cantidad?"));
                        if (cantidad < 0) cantidad = 1;
                    }catch(NumberFormatException ee){
                            cantidad = 1;
                    }
            
            boolean respuesta = BDDInventarios.updateCantidadProductoAsignado(id, id_pro, cantidad);    
            
            if(respuesta){
                javax.swing.JOptionPane.showMessageDialog(this, "Cantidad editada con éxito.");
                llenarLista(BDDInventarios.selectProductosAsignadosMovimiento(id));
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cambiar la cantidad, verifique que el producto tenga suficiente stock.");
            }
        }catch(Exception ee){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto.");
        }
    }//GEN-LAST:event_btnEditarCantidadMouseClicked

    private void btnDesbloquearDatosListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearDatosListaMouseClicked
        this.desbloquearDatosLista(true);
        javax.swing.JOptionPane.showMessageDialog(this, "Datos desbloqueados con éxito.\n" +"Advertencia: Todo cambio hecho se reflejará de manera permanente.");
    }//GEN-LAST:event_btnDesbloquearDatosListaMouseClicked

    private void btnDesbloquearDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearDatosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesbloquearDatosMouseEntered

    private void btnDesbloquearDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearDatosMouseClicked
        this.desbloquearDatosFormulario(true);
        javax.swing.JOptionPane.showMessageDialog(this, "Datos desbloqueados con éxito.\n" +"Advertencia: Todo cambio hecho se reflejará de manera permanente.");
    }//GEN-LAST:event_btnDesbloquearDatosMouseClicked

    private void btnEliminarMovimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMovimientoMouseClicked

        int decision=showConfirmDialog(this,"¿Está seguro que desea eliminar este movimiento?");
        if(decision==0){
            boolean respuesta = BDDInventarios.deleteMovimiento(id);
            
            if(respuesta){
                javax.swing.JOptionPane.showMessageDialog(this, "Movimiento eliminado con éxito.");
                ventanaMovimientos.isAbiertodetallesAsignacion = false;
                dispose();
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar el movimiento.\n" +"NOTA: Asegúrese de que todos sus productos asignados ya haiga sido quitado de la lista.");
            }
        }
    }//GEN-LAST:event_btnEliminarMovimientoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        boolean respuesta = BDDInventarios.updateDatosMovimiento(id,this.txtObservaciones.getText(), this.checkStatus.isSelected());
        
        if (respuesta){
            javax.swing.JOptionPane.showMessageDialog(this, "Movimiento editado con éxito.");
            desbloquearDatosFormulario(false);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo editar el movimiento.");
        }
    }//GEN-LAST:event_btnEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesbloquearDatos;
    private javax.swing.JButton btnDesbloquearDatosLista;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarCantidad;
    private javax.swing.JButton btnEliminarMovimiento;
    private javax.swing.JButton btnQuitarListta;
    private javax.swing.JCheckBox checkStatus;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPersona;
    // End of variables declaration//GEN-END:variables
}
