/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDINVENTARIOS.VISTAS;

import MD.GENERALES.VISTAS.interfazPrincipal;
import MDINVENTARIOS.CONTROLADORES.BDDInventarios;
import MDINVENTARIOS.CONTROLADORES.MDINVENTARIOS;
import MDINVENTARIOS.MODELOS.Clasificacion;
import MDINVENTARIOS.MODELOS.Foto;
import MDINVENTARIOS.MODELOS.Producto;
import MDINVENTARIOS.MODELOS.Status;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan
 */
public final class ventanaDatosProducto extends javax.swing.JFrame {
    
   

    /**
     * Creates new form ventanaDatosProducto
     */
    int id;
    private boolean existefoto = false;
    public ventanaDatosProducto(String nombre,String marca,String modelo) {
        this.setUndecorated(false);
        initComponents();
        
        Producto pro = BDDInventarios.selectProductoFiltrado(nombre,marca,modelo);
        txtcol_pro.setText(pro.getCol_pro());
        txtdes_pro.setText(pro.getDes_pro());
        txtfechacom_pro.setText(pro.getFechcompra_pro());
        txtimp_pro.setText(pro.getImp_pro()+"");
        txtkilm_pro.setText(pro.getKm_pro()+"");
        txtmar_pro.setText(pro.getMar_pro());
        txtmod_pro.setText(pro.getMod_pro());
        txtnofac_pro.setText(pro.getNofact_pro());
        txtnoiden_pro.setText(pro.getCon_pro()+"");
        txtnom_pro.setText(pro.getNom_pro());
        txtnomor_pro.setText(pro.getNomot_pro());
        txtnoserie_pro.setText(pro.getSer_pro());
        txtobs_pro.setText(pro.getObs_pro());
        txtpla_pro.setText(pro.getPla_pro());
        txtservkm_pro.setText(pro.getKm_ser_pro()+"");
        txtstock_pro.setText(pro.getStock_pro()+"");
        txtstockmin_pro.setText(pro.getStockmin_pro()+"");
        txtsubcat_pro.setText(pro.getSubcat_pro());
        
        ArrayList<Clasificacion> clas = BDDInventarios.selectClasificaciones();
        ArrayList<Status> sta = BDDInventarios.selectStatus();
        
        for(int x=0; x < clas.size(); x++){
            Clasificacion temp = clas.get(x);
            this.cmbclasificacion.addItem(temp.getNom_clas());
            if(temp.getId_clas() == pro.getId_cla()){
                cmbclasificacion.setSelectedItem(temp.getNom_clas());
            }
        }
        
        for(int x=0; x < sta.size(); x++){
            Status temp = sta.get(x);
            this.cmbstatus.addItem(temp.getNom_sta());
            if(temp.getId_sta() == pro.getId_sta()){
                cmbstatus.setSelectedItem(temp.getNom_sta());
            }
        }
        
        ArrayList<Foto> foto = BDDInventarios.selectFotos();
        
        for(int x=0; x < foto.size(); x++){
            if (foto.get(x).getId_pro() == pro.getId_pro()){
                ImageIcon fot = new ImageIcon(foto.get(x).getFot_fot());
                Icon icono = new ImageIcon(fot.getImage().getScaledInstance(this.pnlimagenproducto.getWidth(), pnlimagenproducto.getHeight(), Image.SCALE_DEFAULT));
                JLabel etiqueta = new JLabel(icono);
                etiqueta.setSize(pnlimagenproducto.getWidth(), pnlimagenproducto.getHeight());
                pnlimagenproducto.removeAll();
                pnlimagenproducto.add(etiqueta).repaint();
                existefoto = true;
            }
        }
        
        desbloquearBloquearDatos(false);
        
        id = pro.getId_pro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblColorPro1 = new javax.swing.JLabel();
        txtcol_pro = new javax.swing.JTextField();
        lblMarcaPro1 = new javax.swing.JLabel();
        txtmar_pro = new javax.swing.JTextField();
        lblModeloPro1 = new javax.swing.JLabel();
        txtmod_pro = new javax.swing.JTextField();
        lblNumSeriePro1 = new javax.swing.JLabel();
        txtnoserie_pro = new javax.swing.JTextField();
        lblStockPro1 = new javax.swing.JLabel();
        txtstock_pro = new javax.swing.JTextField();
        lblMinimoPro1 = new javax.swing.JLabel();
        txtstockmin_pro = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblNombrePro1 = new javax.swing.JLabel();
        txtnom_pro = new javax.swing.JTextField();
        lblDescripcionPro1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtdes_pro = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        txtfechacom_pro = new javax.swing.JTextField();
        lblFechaCompraPro = new javax.swing.JLabel();
        lblNumFacturaPro = new javax.swing.JLabel();
        txtnofac_pro = new javax.swing.JTextField();
        lblImportePro = new javax.swing.JLabel();
        txtimp_pro = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblClasficPro = new javax.swing.JLabel();
        cmbclasificacion = new javax.swing.JComboBox<>();
        lblEstatusPro = new javax.swing.JLabel();
        cmbstatus = new javax.swing.JComboBox<>();
        lblObservPro = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtobs_pro = new javax.swing.JTextArea();
        lblNumIdentificacionPro = new javax.swing.JLabel();
        txtnoiden_pro = new javax.swing.JTextField();
        lblSubCatPro = new javax.swing.JLabel();
        txtsubcat_pro = new javax.swing.JTextField();
        pnlimagenproducto = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtpla_pro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtnomor_pro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtkilm_pro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtservkm_pro = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnDesbloquearDatos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCambiarFotografia = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos generales:"));

        lblColorPro1.setText("Color:");

        lblMarcaPro1.setText("Marca:");

        lblModeloPro1.setText("Modelo:");

        lblNumSeriePro1.setText("No. Serie:");

        lblStockPro1.setText("Stock:");

        txtstock_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstock_proActionPerformed(evt);
            }
        });

        lblMinimoPro1.setText("Mínimo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblColorPro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcol_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMarcaPro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtmar_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblModeloPro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtmod_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMinimoPro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtstockmin_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblStockPro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtstock_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNumSeriePro1)
                        .addGap(18, 18, 18)
                        .addComponent(txtnoserie_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorPro1)
                    .addComponent(txtcol_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaPro1)
                    .addComponent(txtmar_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloPro1)
                    .addComponent(txtmod_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSeriePro1)
                    .addComponent(txtnoserie_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockPro1)
                    .addComponent(txtstock_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimoPro1)
                    .addComponent(txtstockmin_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 280, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos producto:"));

        lblNombrePro1.setText("Nombre:");

        lblDescripcionPro1.setText("Descripción:");

        txtdes_pro.setColumns(20);
        txtdes_pro.setRows(5);
        jScrollPane4.setViewportView(txtdes_pro);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblNombrePro1)
                        .addGap(18, 18, 18)
                        .addComponent(txtnom_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescripcionPro1)
                    .addComponent(jScrollPane4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePro1)
                    .addComponent(txtnom_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDescripcionPro1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 250));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos adquicision:"));

        lblFechaCompraPro.setText("Fecha de compra: ");

        lblNumFacturaPro.setText("No. Factura:");

        lblImportePro.setText("Importe:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaCompraPro)
                    .addComponent(lblNumFacturaPro)
                    .addComponent(lblImportePro))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtimp_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnofac_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechacom_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaCompraPro)
                    .addComponent(txtfechacom_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFacturaPro)
                    .addComponent(txtnofac_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImportePro)
                    .addComponent(txtimp_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 330, 140));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Caracteristicas del producto:"));

        lblClasficPro.setText("Clasificación:");

        cmbclasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clasificación" }));

        lblEstatusPro.setText("Status:");

        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Status" }));

        lblObservPro.setText("Observaciones:");

        txtobs_pro.setColumns(20);
        txtobs_pro.setRows(5);
        jScrollPane3.setViewportView(txtobs_pro);

        lblNumIdentificacionPro.setText("No. Identificación:");

        lblSubCatPro.setText("Sub Categoría:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblSubCatPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(txtsubcat_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasficPro)
                            .addComponent(lblEstatusPro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbclasificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblObservPro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblNumIdentificacionPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnoiden_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasficPro)
                    .addComponent(cmbclasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstatusPro)
                    .addComponent(cmbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblObservPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumIdentificacionPro)
                            .addComponent(txtnoiden_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSubCatPro))
                    .addComponent(txtsubcat_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 330, 370));

        pnlimagenproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout pnlimagenproductoLayout = new javax.swing.GroupLayout(pnlimagenproducto);
        pnlimagenproducto.setLayout(pnlimagenproductoLayout);
        pnlimagenproductoLayout.setHorizontalGroup(
            pnlimagenproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        pnlimagenproductoLayout.setVerticalGroup(
            pnlimagenproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        jPanel1.add(pnlimagenproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 360, 310));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos vehiculo:"));

        jLabel11.setText("Placa:");

        jLabel12.setText("No. Motor:");

        jLabel20.setText("Kilometraje:");

        jLabel21.setText("Kilometraje serv.:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpla_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtkilm_pro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtservkm_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnomor_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpla_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomor_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkilm_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtservkm_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 360, 200));

        jTabbedPane1.addTab("Datos generales", jPanel1);

        btnEditar.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        btnDesbloquearDatos.setBackground(new java.awt.Color(255, 255, 204));
        btnDesbloquearDatos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDesbloquearDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/desbloquear.png"))); // NOI18N
        btnDesbloquearDatos.setText("Desbloquear Datos");
        btnDesbloquearDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearDatosMouseClicked(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 204));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnCambiarFotografia.setBackground(new java.awt.Color(255, 255, 204));
        btnCambiarFotografia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCambiarFotografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/image.png"))); // NOI18N
        btnCambiarFotografia.setText("Cambiar Fotografia");
        btnCambiarFotografia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarFotografiaMouseClicked(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 204));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarFotografia)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesbloquearDatos)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCambiarFotografia)
                        .addComponent(btnDesbloquearDatos)
                        .addComponent(btnEditar)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered

    }//GEN-LAST:event_jTabbedPane1MouseEntered

    private void txtstock_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstock_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstock_proActionPerformed

    private void btnDesbloquearDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearDatosMouseClicked
        desbloquearBloquearDatos(true);
        javax.swing.JOptionPane.showMessageDialog(this, "Ahora ya puede trabajar con los datos.\n NOTA: Cualquier cambio hecho después de presionar Editar, no se podrá recuperar.");
    }//GEN-LAST:event_btnDesbloquearDatosMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        interfazPrincipal.isAbiertoDetallesProducto = false;
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        interfazPrincipal.isAbiertoDetallesProducto = false;
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este producto?", "ELIMINAR PRODUCTO", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            if(existefoto){
                BDDInventarios.deleteFoto(id);
            }
            if(BDDInventarios.deleteProducto(id)){
                javax.swing.JOptionPane.showMessageDialog(this, "Producto eliminado con éxito.");
                interfazPrincipal.isAbiertoDetallesProducto = false;
                dispose();
                return;
            }
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar el producto.");
        }
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        int id_pro = id;
        
        int con_pro;
        try{
            con_pro = Integer.parseInt(this.txtnoiden_pro.getText());
        }catch(NumberFormatException e){
            con_pro = 0;
            txtnoiden_pro.setText("0");
        }
        
        String subcat_pro = this.txtsubcat_pro.getText();
        String nom_pro = this.txtnom_pro.getText();
        String des_pro = this.txtdes_pro.getText();
        String mar_pro = this.txtmar_pro.getText();
        String mod_pro = this.txtmod_pro.getText();
        String ser_pro = this.txtnoserie_pro.getText();
        String col_pro = this.txtcol_pro.getText();
        String pla_pro = this.txtpla_pro.getText();
        String nomot_pro = this.txtnomor_pro.getText();
        String fechcompra_pro = this.txtfechacom_pro.getText();
        String nofact_pro = this.txtnofac_pro.getText();
                
        double imp_pro;
        try{
            imp_pro = Double.parseDouble(this.txtimp_pro.getText());
        }catch(NumberFormatException e){
            imp_pro = 0;
            txtimp_pro.setText("0");
        }
        
        if (imp_pro < 0){
            javax.swing.JOptionPane.showMessageDialog(this, "¡Opsss! No se permite que le importe sea un numero negativo.");
            return;                    
        }
        
        String obs_pro = this.txtobs_pro.getText();
                
        int stock_pro;
        try{
            stock_pro = Integer.parseInt(this.txtstock_pro.getText());
        }catch(NumberFormatException e){
            stock_pro = 1;
            txtstock_pro.setText("0");
        }
        
        int stockmin_pro;
        try{
            stockmin_pro =  Integer.parseInt(this.txtstockmin_pro.getText());
        }catch(NumberFormatException e){
            stockmin_pro = 1;
            txtstockmin_pro.setText("0");
        }
        
        if (stock_pro < 0 || stockmin_pro < 0){
            javax.swing.JOptionPane.showMessageDialog(this, "¡Opsss! No se permiten números negativos en los stocks.");
            return;                    
        }
        
        int km_pro;
        int km_ser_pro;
        
        try{
            km_pro =  Integer.parseInt(this.txtkilm_pro.getText());
            km_ser_pro =  Integer.parseInt(this.txtservkm_pro.getText());
        }catch(NumberFormatException e){
            km_pro =  0;
            km_ser_pro =  0;
            txtkilm_pro.setText("0");
            txtservkm_pro.setText("0");
        }
        
        if(this.cmbclasificacion.getSelectedIndex() == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "¡Opsss! Seleccione una clasificación.");
            return; 
        }
        
        if(this.cmbstatus.getSelectedIndex() == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "¡Opsss! Seleccione un Status.");
            return; 
        }
      /*  
        if(!MDINVENTARIOS.validarFechaFormato(fechcompra_pro)){
            javax.swing.JOptionPane.showMessageDialog(this, "¡Opsss! Fecha con formato incorrecto. El formato correcto es:  EJEM. 2017/12/31");
            return;
        }
        */
        int id_cla = BDDInventarios.selectIdCLasificacion((String)this.cmbclasificacion.getSelectedItem());
        int id_sta = BDDInventarios.selectIdStatus((String)this.cmbstatus.getSelectedItem());
        
        Producto produto = new Producto(id_pro, con_pro, subcat_pro, nom_pro, des_pro, mar_pro, mod_pro, ser_pro, col_pro, pla_pro, nomot_pro, fechcompra_pro, nofact_pro, imp_pro, obs_pro, stock_pro, stockmin_pro, km_pro, km_ser_pro, id_cla, id_sta);
        
        MDINVENTARIOS mdinv = new MDINVENTARIOS();
        String  res = mdinv.modificarProducto(produto);
        if(res.equals("Producto modificado con éxito.")){
            javax.swing.JOptionPane.showMessageDialog(this, res);
            interfazPrincipal.isAbiertoDetallesProducto = false;
            dispose();
        }
        
     
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnCambiarFotografiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarFotografiaMouseClicked
        String ruta = "";
        JFileChooser file=new JFileChooser();
        file.setDialogTitle("Cargar Imagen...");
        int seleccion = file.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION){
            File imagen = file.getSelectedFile();
            ruta = imagen.getPath();
            ImageIcon fot = new ImageIcon(ruta);
            Icon icono = new ImageIcon(fot.getImage().getScaledInstance(pnlimagenproducto.getWidth(), pnlimagenproducto.getHeight(), Image.SCALE_DEFAULT));
            JLabel etiqueta = new JLabel(icono);
            etiqueta.setSize(pnlimagenproducto.getWidth(), pnlimagenproducto.getHeight());
            pnlimagenproducto.removeAll();
            pnlimagenproducto.add(etiqueta).repaint();
        }
        
        MDINVENTARIOS mi = new MDINVENTARIOS();
        String ft = mi.modificarFoto(ruta, id);
        javax.swing.JOptionPane.showMessageDialog(this, ft);
    }//GEN-LAST:event_btnCambiarFotografiaMouseClicked
    
    public void desbloquearBloquearDatos(boolean valor){
        txtcol_pro.setEditable(valor);
        txtdes_pro.setEditable(valor);
        txtfechacom_pro.setEditable(valor);
        txtimp_pro.setEditable(valor);
        txtkilm_pro.setEditable(valor);
        txtmar_pro.setEditable(valor);
        txtmod_pro.setEditable(valor);
        txtnofac_pro.setEditable(valor);
        txtnoiden_pro.setEditable(valor);
        txtnom_pro.setEditable(valor);
        txtnomor_pro.setEditable(valor);
        txtnoserie_pro.setEditable(valor);
        txtobs_pro.setEditable(valor);
        txtpla_pro.setEditable(valor);
        txtservkm_pro.setEditable(valor);
        txtstock_pro.setEditable(valor);
        txtstockmin_pro.setEditable(valor);
        txtsubcat_pro.setEditable(valor);
        cmbclasificacion.setEnabled(valor);
        cmbstatus.setEnabled(valor);
        this.btnEditar.setEnabled(valor);
        this.btnEliminar.setEnabled(valor);
        this.btnCambiarFotografia.setEnabled(valor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarFotografia;
    private javax.swing.JButton btnDesbloquearDatos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbclasificacion;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblClasficPro;
    private javax.swing.JLabel lblColorPro1;
    private javax.swing.JLabel lblDescripcionPro1;
    private javax.swing.JLabel lblEstatusPro;
    private javax.swing.JLabel lblFechaCompraPro;
    private javax.swing.JLabel lblImportePro;
    private javax.swing.JLabel lblMarcaPro1;
    private javax.swing.JLabel lblMinimoPro1;
    private javax.swing.JLabel lblModeloPro1;
    private javax.swing.JLabel lblNombrePro1;
    private javax.swing.JLabel lblNumFacturaPro;
    private javax.swing.JLabel lblNumIdentificacionPro;
    private javax.swing.JLabel lblNumSeriePro1;
    private javax.swing.JLabel lblObservPro;
    private javax.swing.JLabel lblStockPro1;
    private javax.swing.JLabel lblSubCatPro;
    private javax.swing.JPanel pnlimagenproducto;
    private javax.swing.JTextField txtcol_pro;
    private javax.swing.JTextArea txtdes_pro;
    private javax.swing.JTextField txtfechacom_pro;
    private javax.swing.JTextField txtimp_pro;
    private javax.swing.JTextField txtkilm_pro;
    private javax.swing.JTextField txtmar_pro;
    private javax.swing.JTextField txtmod_pro;
    private javax.swing.JTextField txtnofac_pro;
    private javax.swing.JTextField txtnoiden_pro;
    private javax.swing.JTextField txtnom_pro;
    private javax.swing.JTextField txtnomor_pro;
    private javax.swing.JTextField txtnoserie_pro;
    private javax.swing.JTextArea txtobs_pro;
    private javax.swing.JTextField txtpla_pro;
    private javax.swing.JTextField txtservkm_pro;
    private javax.swing.JTextField txtstock_pro;
    private javax.swing.JTextField txtstockmin_pro;
    private javax.swing.JTextField txtsubcat_pro;
    // End of variables declaration//GEN-END:variables
}
