/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MD.PERSONAL.VISTAS;
import MDPERSONAL.CONTROLADORES.BDDPersonal;
import MDPERSONAL.CONTROLADORES.BDPERSONAL;
import MDPERSONAL.MODELOS.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import static javax.swing.JOptionPane.showMessageDialog;
//utilizar clase Validaciones

import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Edgar
 */
public class InterfazInsertarPersonal extends javax.swing.JFrame {
BDPERSONAL metodo =  new BDPERSONAL();

ValidacionesPersonal valida =new ValidacionesPersonal();

     int x=0;
     int y=0;
    /**
     * Creates new form InsetarPersonal
     */
    public InterfazInsertarPersonal() {
        initComponents();
        setLocationRelativeTo(null);
           //ocultara las palomitas por defecto al iniciarse la ventana
       p1.setVisible(false);
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p6.setVisible(false);
       p7.setVisible(false);
       p8.setVisible(false);
       p9.setVisible(false);
       p10.setVisible(false);
       p11.setVisible(false);
       p12.setVisible(false);
       p13.setVisible(false);
       p14.setVisible(false);
       p15.setVisible(false);
        /*CARGAR CMBPuesto*/
       
        ArrayList<Puesto> arrayPuesto = BDPERSONAL.selectPuesto();
        for(int i = 0; i < arrayPuesto.size(); i++){
            this.cmbPuestoP.addItem(arrayPuesto.get(i).getNom_pue());
            
        }
        
       /*CARGAR CMBPuesto*/ 
            ArrayList<Area> arrayArea = BDPERSONAL.selectArea();
        for(int i = 0; i < arrayArea.size(); i++){
            
            this.cmbAreaP.addItem(arrayArea.get(i).getNom_are());
            
        }
       /*
        pnlAgregarPersonal.setVisible(false);
        pnlAgregarPuesto.setVisible(false);
        pnlAgregarArea.setVisible(false);
        pnlConsultar.setVisible(false);
        try {
        ArrayList<String > puestosDisponibles = p.extraerPuestos();
        cmbPuesto.removeAllItems();
        for(int i=0; i<puestosDisponibles.size();i++){
        cmbPuesto.addItem(puestosDisponibles.get(i));
        }
        
        } catch (SQLException ex) {
        Logger.getLogger(InterfazInsertarPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
        ArrayList<String > areasDisponibles = p.extraerAreas();
        cmbAreaP.removeAllItems();
        for(int i=0; i<areasDisponibles.size();i++){
        cmbAreaP.addItem(areasDisponibles.get(i));
        }
        
        } catch (SQLException ex) {
        Logger.getLogger(InterfazInsertarPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
        modeloTabla=(DefaultTableModel) tblConsultaPersonal.getModel();
        llenarPersonal();
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgregarPersonal = new javax.swing.JPanel();
        lblCerrarPnl = new javax.swing.JLabel();
        lblApellidoPat = new javax.swing.JLabel();
        lblTelP = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        txtApellidoPatP = new javax.swing.JTextField();
        lblApellidoPat1 = new javax.swing.JLabel();
        txtFechaNacP = new javax.swing.JTextField();
        lblCredP = new javax.swing.JLabel();
        txtColP = new javax.swing.JTextField();
        lblColP = new javax.swing.JLabel();
        lblCallP = new javax.swing.JLabel();
        lblNumP = new javax.swing.JLabel();
        lblcpP = new javax.swing.JLabel();
        txtCalleP = new javax.swing.JTextField();
        txtNumP = new javax.swing.JTextField();
        txtcpP = new javax.swing.JTextField();
        txtTelP = new javax.swing.JTextField();
        btnRegistarP = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p14 = new javax.swing.JLabel();
        p15 = new javax.swing.JLabel();
        lblInfoF = new javax.swing.JLabel();
        btnBorrarTP = new javax.swing.JButton();
        lblNombreP3 = new javax.swing.JLabel();
        lblRfcP = new javax.swing.JLabel();
        lblLicMP = new javax.swing.JLabel();
        txtCurpP = new javax.swing.JTextField();
        txtLicMP = new javax.swing.JTextField();
        txtRfcP = new javax.swing.JTextField();
        txtCredencialP = new javax.swing.JTextField();
        lblInfoF1 = new javax.swing.JLabel();
        lblCredP1 = new javax.swing.JLabel();
        lblCredP2 = new javax.swing.JLabel();
        cmbAreaP = new javax.swing.JComboBox<>();
        cmbPuestoP = new javax.swing.JComboBox<>();
        lblApellidoMat = new javax.swing.JLabel();
        lblRfcP1 = new javax.swing.JLabel();
        txtApellidoMat = new javax.swing.JTextField();
        lblInformacionB3 = new javax.swing.JLabel();
        lblInformacionB4 = new javax.swing.JLabel();
        lblInformacionB2 = new javax.swing.JLabel();
        LBLMOVER = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAgregarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgregarPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlAgregarPersonal.setForeground(new java.awt.Color(255, 255, 204));
        pnlAgregarPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrarPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarPnl.png"))); // NOI18N
        lblCerrarPnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarPnlMouseClicked(evt);
            }
        });
        pnlAgregarPersonal.add(lblCerrarPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 30, -1));

        lblApellidoPat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblApellidoPat.setText("Fecha de Nacimiento");
        pnlAgregarPersonal.add(lblApellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblTelP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTelP.setText("Telefono");
        pnlAgregarPersonal.add(lblTelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        txtNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePActionPerformed(evt);
            }
        });
        txtNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombrePKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombrePKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, -1));

        txtApellidoPatP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoPatPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPatPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtApellidoPatP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        lblApellidoPat1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblApellidoPat1.setText("Apellido Paterno");
        pnlAgregarPersonal.add(lblApellidoPat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtFechaNacP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaNacP.setText("aaaa-mm-dd");
        txtFechaNacP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaNacPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaNacPFocusLost(evt);
            }
        });
        txtFechaNacP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaNacPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFechaNacPMouseEntered(evt);
            }
        });
        txtFechaNacP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacPActionPerformed(evt);
            }
        });
        txtFechaNacP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaNacPKeyPressed(evt);
            }
        });
        pnlAgregarPersonal.add(txtFechaNacP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, -1));

        lblCredP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCredP.setText("Puesto ");
        pnlAgregarPersonal.add(lblCredP, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 150, -1));

        txtColP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtColPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtColP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, -1));

        lblColP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblColP.setText("Colonia");
        pnlAgregarPersonal.add(lblColP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        lblCallP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCallP.setText("Calle");
        pnlAgregarPersonal.add(lblCallP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        lblNumP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumP.setText("Numero");
        pnlAgregarPersonal.add(lblNumP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        lblcpP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblcpP.setText("Codigo Postal");
        pnlAgregarPersonal.add(lblcpP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        txtCalleP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCallePKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCallePKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtCalleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 120, -1));

        txtNumP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtNumP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 120, -1));

        txtcpP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcpPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcpPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtcpP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 120, -1));

        txtTelP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelPActionPerformed(evt);
            }
        });
        txtTelP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtTelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 120, -1));

        btnRegistarP.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistarP.setText("Guardar");
        btnRegistarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarPActionPerformed(evt);
            }
        });
        pnlAgregarPersonal.add(btnRegistarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 70, 30));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 20, 20));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 20, 20));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 20, 20));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 20, 20));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 20, 20));

        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 20, 20));

        p7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 20, 20));

        p8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 20, 20));

        p9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 20, 20));

        p10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 20, 20));

        p11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 20, 20));

        p12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 20, 20));

        p13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 20, 20));

        p14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 20, 20));

        p15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        pnlAgregarPersonal.add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 20, 20));

        lblInfoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        lblInfoF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInfoF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoFMouseClicked(evt);
            }
        });
        pnlAgregarPersonal.add(lblInfoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, 30));

        btnBorrarTP.setBackground(new java.awt.Color(255, 255, 255));
        btnBorrarTP.setText("Limpiar");
        btnBorrarTP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrarTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTPActionPerformed(evt);
            }
        });
        pnlAgregarPersonal.add(btnBorrarTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 80, 30));

        lblNombreP3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreP3.setText("Nombre");
        pnlAgregarPersonal.add(lblNombreP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        lblRfcP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRfcP.setText("Curp");
        pnlAgregarPersonal.add(lblRfcP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 40, -1));

        lblLicMP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLicMP.setText("Licencia de Manejo");
        pnlAgregarPersonal.add(lblLicMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 150, -1));

        txtCurpP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCurpP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtCurpPMouseMoved(evt);
            }
        });
        txtCurpP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCurpPMouseExited(evt);
            }
        });
        txtCurpP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCurpPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurpPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtCurpP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 140, -1));

        txtLicMP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtLicMP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtLicMPMouseMoved(evt);
            }
        });
        txtLicMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLicMPMouseExited(evt);
            }
        });
        txtLicMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicMPActionPerformed(evt);
            }
        });
        txtLicMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLicMPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicMPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtLicMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 140, -1));

        txtRfcP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtRfcP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtRfcPMouseMoved(evt);
            }
        });
        txtRfcP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRfcPMouseExited(evt);
            }
        });
        txtRfcP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcPActionPerformed(evt);
            }
        });
        txtRfcP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRfcPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRfcPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtRfcP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 140, -1));

        txtCredencialP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCredencialP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtCredencialPMouseMoved(evt);
            }
        });
        txtCredencialP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCredencialPMouseExited(evt);
            }
        });
        txtCredencialP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCredencialPActionPerformed(evt);
            }
        });
        txtCredencialP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCredencialPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCredencialPKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtCredencialP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 140, -1));

        lblInfoF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        lblInfoF1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInfoF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoF1MouseClicked(evt);
            }
        });
        pnlAgregarPersonal.add(lblInfoF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 30));

        lblCredP1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCredP1.setText("Clave de Elector");
        pnlAgregarPersonal.add(lblCredP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 160, -1));

        lblCredP2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCredP2.setText("Area Perteneciente");
        pnlAgregarPersonal.add(lblCredP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 150, -1));

        cmbAreaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Area", " " }));
        cmbAreaP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbAreaP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAreaPItemStateChanged(evt);
            }
        });
        cmbAreaP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbAreaPFocusGained(evt);
            }
        });
        cmbAreaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaPActionPerformed(evt);
            }
        });
        pnlAgregarPersonal.add(cmbAreaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 150, -1));

        cmbPuestoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el puesto", " " }));
        cmbPuestoP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbPuestoP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPuestoPItemStateChanged(evt);
            }
        });
        cmbPuestoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbPuestoPFocusGained(evt);
            }
        });
        cmbPuestoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPuestoPActionPerformed(evt);
            }
        });
        pnlAgregarPersonal.add(cmbPuestoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 150, -1));

        lblApellidoMat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblApellidoMat.setText("Apellido Materno");
        pnlAgregarPersonal.add(lblApellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblRfcP1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRfcP1.setText("Rfc");
        pnlAgregarPersonal.add(lblRfcP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 40, -1));

        txtApellidoMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoMatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMatKeyReleased(evt);
            }
        });
        pnlAgregarPersonal.add(txtApellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, -1));

        lblInformacionB3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Basica"));
        pnlAgregarPersonal.add(lblInformacionB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, 190));

        lblInformacionB4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de Contacto"));
        pnlAgregarPersonal.add(lblInformacionB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 400, 190));

        lblInformacionB2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Legal"));
        pnlAgregarPersonal.add(lblInformacionB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 400, 190));

        LBLMOVER.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        LBLMOVER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LBLMOVERMouseDragged(evt);
            }
        });
        LBLMOVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LBLMOVERMousePressed(evt);
            }
        });
        pnlAgregarPersonal.add(LBLMOVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 70));

        getContentPane().add(pnlAgregarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarPnlMouseClicked
       dispose();
        
    }//GEN-LAST:event_lblCerrarPnlMouseClicked

    private void txtNombrePKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePKeyPressed
  valida.validarNombre(txtNombreP,p1);
    }//GEN-LAST:event_txtNombrePKeyPressed

    private void txtApellidoPatPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPatPKeyPressed
    valida.validarApPat(txtApellidoPatP,p2); 
    }//GEN-LAST:event_txtApellidoPatPKeyPressed

    private void txtFechaNacPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaNacPFocusGained
        
    }//GEN-LAST:event_txtFechaNacPFocusGained

    private void txtFechaNacPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaNacPFocusLost
         
    }//GEN-LAST:event_txtFechaNacPFocusLost

    private void txtFechaNacPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacPActionPerformed

    private void txtTelPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelPActionPerformed

    private void btnRegistarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarPActionPerformed
                 
   //Si las palomitas son verdes y es correcto se podra insertar personal     
   if(p1.isVisible()==true&&p2.isVisible()==true&&p3.isVisible()==true&&p4.isVisible()==true&&p5.isVisible()==true&&
           p6.isVisible()==true&&p7.isVisible()==true&&p8.isVisible()==true&&p9.isVisible()==true&&p10.isVisible()==true&&
           p11.isVisible()==true&&p12.isVisible()==true&&p13.isVisible()==true&&p14.isVisible()==true&&
           p15.isVisible()==true){
     
        Personal persona = new Personal(txtNombreP.getText(),
        txtApellidoPatP.getText(),
        txtApellidoMat.getText(),
         txtCalleP.getText(),
        txtNumP.getText(),
        txtColP.getText(),
       Integer.parseInt(txtcpP.getText()),
        txtTelP.getText(),
         txtFechaNacP.getText(),
        txtCurpP.getText(),
         txtRfcP.getText(),
         txtLicMP.getText(),
       txtCredencialP.getText(),
       cmbAreaP.getSelectedIndex(),
       cmbPuestoP.getSelectedIndex());

        //Aqui mandara a insertar un objeto tipo persona a la bf
     metodo.insertarPersonal(persona);
   }else{
       showMessageDialog(null,"Por favor antes de registrar nuevo personal"+"\n"+"verifica que los campos sean correctos");
   }
    }//GEN-LAST:event_btnRegistarPActionPerformed

    private void btnBorrarTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTPActionPerformed
       p1.setVisible(false);
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p6.setVisible(false);
       p7.setVisible(false);
       p8.setVisible(false);
       p9.setVisible(false);
       p10.setVisible(false);
       p11.setVisible(false);
       p12.setVisible(false);
       p13.setVisible(false);
       p14.setVisible(false);
       p15.setVisible(false);
       cmbAreaP.setSelectedIndex(0);
       cmbPuestoP.setSelectedIndex(0);
       
       txtFechaNacP.setText("aaaa-mm-dd");
        txtFechaNacP.setForeground(Color.black);
        txtRfcP.setText(null);
        txtTelP.setText(null);
        txtApellidoPatP.setText(null);
        txtCalleP.setText(null);
        txtColP.setText(null);
        txtCredencialP.setText(null);
        txtCurpP.setText(null);
        txtLicMP.setText(null);
        txtNombreP.setText(null);
        txtcpP.setText(null);
        txtNumP.setText(null);

    }//GEN-LAST:event_btnBorrarTPActionPerformed

    private void txtLicMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicMPActionPerformed

    private void txtRfcPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcPActionPerformed

    private void txtCredencialPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCredencialPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCredencialPActionPerformed

    private void txtApellidoMatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMatKeyPressed
valida.validarApMat(txtApellidoMat,p3);  
    }//GEN-LAST:event_txtApellidoMatKeyPressed

    private void txtNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePActionPerformed

    private void txtNombrePuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePuestoActionPerformed

    private void cmbAreaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaPActionPerformed
    
    }//GEN-LAST:event_cmbAreaPActionPerformed

    private void cmbPuestoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPuestoPActionPerformed
       
    }//GEN-LAST:event_cmbPuestoPActionPerformed

    private void txtFechaNacPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaNacPMouseClicked
      txtFechaNacP.setText("");
    }//GEN-LAST:event_txtFechaNacPMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     cmbAreaP.removeItemAt(1);  
   
     cmbPuestoP.removeItemAt(1); 
       
    }//GEN-LAST:event_formWindowOpened

    private void txtNombrePKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePKeyReleased
    valida.validarNombre(txtNombreP,p1);
    }//GEN-LAST:event_txtNombrePKeyReleased

    private void txtApellidoPatPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPatPKeyReleased
  valida.validarNombre(txtNombreP,p1);
    }//GEN-LAST:event_txtApellidoPatPKeyReleased

    private void txtApellidoMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMatKeyReleased
valida.validarApMat(txtApellidoMat,p3);  
    }//GEN-LAST:event_txtApellidoMatKeyReleased

    private void txtColPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColPKeyPressed
valida.validarCol(txtColP,p5);  
    }//GEN-LAST:event_txtColPKeyPressed

    private void txtColPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColPKeyReleased
valida.validarCol(txtColP,p5);    
    }//GEN-LAST:event_txtColPKeyReleased

    private void txtFechaNacPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaNacPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacPMouseEntered

    private void txtFechaNacPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNacPKeyPressed
      valida.validarFechaNacP(txtFechaNacP,p4);
    }//GEN-LAST:event_txtFechaNacPKeyPressed

    private void txtCallePKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCallePKeyPressed
     valida.validarCalle(txtCalleP,p6);
    }//GEN-LAST:event_txtCallePKeyPressed

    private void txtCallePKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCallePKeyReleased
       valida.validarCalle(txtCalleP,p6);
    }//GEN-LAST:event_txtCallePKeyReleased

    private void txtNumPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPKeyPressed
       valida.validarNumCalle(txtNumP,p7);
    }//GEN-LAST:event_txtNumPKeyPressed

    private void txtNumPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPKeyReleased
      valida.validarNumCalle(txtNumP,p7);
    }//GEN-LAST:event_txtNumPKeyReleased

    private void txtcpPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpPKeyPressed
      valida.validarCodigoP(txtcpP,p8);
    }//GEN-LAST:event_txtcpPKeyPressed

    private void txtcpPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpPKeyReleased
       valida.validarCodigoP(txtcpP,p8);
    }//GEN-LAST:event_txtcpPKeyReleased

    private void txtTelPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelPKeyPressed
      valida.validarTel(txtTelP,p9);
    }//GEN-LAST:event_txtTelPKeyPressed

    private void txtTelPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelPKeyReleased
     valida.validarTel(txtTelP,p9);
    }//GEN-LAST:event_txtTelPKeyReleased

    private void txtCurpPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpPKeyPressed
     valida.validarCurp(txtCurpP,p10);
    }//GEN-LAST:event_txtCurpPKeyPressed

    private void txtCurpPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpPKeyReleased
        valida.validarCurp(txtCurpP,p10);
    }//GEN-LAST:event_txtCurpPKeyReleased

    private void txtRfcPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcPKeyPressed
     valida.validarRFC(txtRfcP,p11);
    }//GEN-LAST:event_txtRfcPKeyPressed

    private void txtRfcPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcPKeyReleased
       valida.validarRFC(txtRfcP,p11);
    }//GEN-LAST:event_txtRfcPKeyReleased

    private void LBLMOVERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLMOVERMousePressed
          //para poder arrastar la ventana
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_LBLMOVERMousePressed

    private void LBLMOVERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLMOVERMouseDragged
        //Para mover la ventana
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);

    }//GEN-LAST:event_LBLMOVERMouseDragged

    private void cmbAreaPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAreaPItemStateChanged
      valida.validarCmbArea(cmbAreaP,p14);  
     
    }//GEN-LAST:event_cmbAreaPItemStateChanged

    private void cmbPuestoPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPuestoPItemStateChanged
       valida.validarCmbPuesto(cmbPuestoP,p15);  
    }//GEN-LAST:event_cmbPuestoPItemStateChanged

    private void txtCredencialPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCredencialPKeyPressed
     valida.validarClaveElector(txtCredencialP,p13);
    }//GEN-LAST:event_txtCredencialPKeyPressed

    private void lblInfoFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoFMouseClicked
     showMessageDialog(null,"El numero telefonico debe llevar el formato:"+"\n"+
             "10 digitos para el numero ");
    }//GEN-LAST:event_lblInfoFMouseClicked

    private void lblInfoF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoF1MouseClicked
       showMessageDialog(null,"El formato de la fecha debe ser:"+"\n"+
             "4 digitos para el año - 2 digitos para el mes -2 digitos para el dia ");  
    }//GEN-LAST:event_lblInfoF1MouseClicked

    private void txtLicMPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicMPKeyPressed
      valida.validarLicM(txtLicMP,p12);
    }//GEN-LAST:event_txtLicMPKeyPressed

    private void txtLicMPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicMPKeyReleased
        valida.validarLicM(txtLicMP,p12);
    }//GEN-LAST:event_txtLicMPKeyReleased

    private void txtCredencialPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCredencialPKeyReleased
        valida.validarClaveElector(txtCredencialP,p13);
    }//GEN-LAST:event_txtCredencialPKeyReleased

    private void cmbAreaPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbAreaPFocusGained
   
    }//GEN-LAST:event_cmbAreaPFocusGained

    private void cmbPuestoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbPuestoPFocusGained
     
    }//GEN-LAST:event_cmbPuestoPFocusGained

    private void txtCurpPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCurpPMouseMoved
        valida.validarCurp(txtCurpP,p10);
    }//GEN-LAST:event_txtCurpPMouseMoved

    private void txtRfcPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRfcPMouseMoved
     valida.validarRFC(txtRfcP,p11);
    }//GEN-LAST:event_txtRfcPMouseMoved

    private void txtRfcPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRfcPMouseExited
     valida.validarRFC(txtRfcP,p11);
    }//GEN-LAST:event_txtRfcPMouseExited

    private void txtCurpPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCurpPMouseExited
         valida.validarCurp(txtCurpP,p10);
    }//GEN-LAST:event_txtCurpPMouseExited

    private void txtLicMPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLicMPMouseExited
      valida.validarLicM(txtLicMP,p12);
    }//GEN-LAST:event_txtLicMPMouseExited

    private void txtLicMPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLicMPMouseMoved
     valida.validarLicM(txtLicMP,p12);
    }//GEN-LAST:event_txtLicMPMouseMoved

    private void txtCredencialPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCredencialPMouseExited
       valida.validarClaveElector(txtCredencialP,p13);
    }//GEN-LAST:event_txtCredencialPMouseExited

    private void txtCredencialPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCredencialPMouseMoved
       valida.validarClaveElector(txtCredencialP,p13);
    }//GEN-LAST:event_txtCredencialPMouseMoved

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInsertarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInsertarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInsertarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInsertarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInsertarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLMOVER;
    private javax.swing.JButton btnBorrarTP;
    private javax.swing.JButton btnRegistarP;
    private javax.swing.JComboBox<String> cmbAreaP;
    private javax.swing.JComboBox<String> cmbPuestoP;
    private javax.swing.JLabel lblApellidoMat;
    private javax.swing.JLabel lblApellidoPat;
    private javax.swing.JLabel lblApellidoPat1;
    private javax.swing.JLabel lblCallP;
    private javax.swing.JLabel lblCerrarPnl;
    private javax.swing.JLabel lblColP;
    private javax.swing.JLabel lblCredP;
    private javax.swing.JLabel lblCredP1;
    private javax.swing.JLabel lblCredP2;
    private javax.swing.JLabel lblInfoF;
    private javax.swing.JLabel lblInfoF1;
    private javax.swing.JLabel lblInformacionB2;
    private javax.swing.JLabel lblInformacionB3;
    private javax.swing.JLabel lblInformacionB4;
    private javax.swing.JLabel lblLicMP;
    private javax.swing.JLabel lblNombreP3;
    private javax.swing.JLabel lblNumP;
    private javax.swing.JLabel lblRfcP;
    private javax.swing.JLabel lblRfcP1;
    private javax.swing.JLabel lblTelP;
    private javax.swing.JLabel lblcpP;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p13;
    private javax.swing.JLabel p14;
    private javax.swing.JLabel p15;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    private javax.swing.JPanel pnlAgregarPersonal;
    private javax.swing.JTextField txtApellidoMat;
    private javax.swing.JTextField txtApellidoPatP;
    private javax.swing.JTextField txtCalleP;
    private javax.swing.JTextField txtColP;
    private javax.swing.JTextField txtCredencialP;
    private javax.swing.JTextField txtCurpP;
    private javax.swing.JTextField txtFechaNacP;
    private javax.swing.JTextField txtLicMP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtNumP;
    private javax.swing.JTextField txtRfcP;
    private javax.swing.JTextField txtTelP;
    private javax.swing.JTextField txtcpP;
    // End of variables declaration//GEN-END:variables
}
