/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MD.PERSONAL.VISTAS;

import MDPERSONAL.CONTROLADORES.BDPERSONAL;
import MDPERSONAL.MODELOS.Personal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanramon
 */
public class InterfazEliminarPersonal extends javax.swing.JFrame {

  //Avriables para poder mover la ventana
    int x=0;
    int y=0;
    BDPERSONAL metodo=new BDPERSONAL();
        DefaultTableModel modeloTabla = new DefaultTableModel();
     
    public InterfazEliminarPersonal() {
        initComponents();
        setLocationRelativeTo(null);
        
        //cargara lso nombres de las personas registradas en el sistema en el cmb
      llenarPersonal();
      
      
        /*CARGAR TABLA DE PERSONAL*/
           modeloTabla=(DefaultTableModel) tblConsultaPersonal.getModel();
       try {
            for(int i=0;i<modeloTabla.getRowCount();i++){
                modeloTabla.removeRow(i);
            }
            metodo.llenadoConsultaPersonalCurp(modeloTabla);

        } catch (SQLException ex) {
             
        }
      
       /*CARGAR TABLA DE PERSONAL*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEliminarPersonal = new javax.swing.JPanel();
        cmbEliminarPersonal = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnEliminarPersonal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsultaPersonal = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMover = new javax.swing.JLabel();
        lbljohasijd1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEliminarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        pnlEliminarPersonal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEliminarPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbEliminarPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la persona" }));
        cmbEliminarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbEliminarPersonal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEliminarPersonalItemStateChanged(evt);
            }
        });
        pnlEliminarPersonal.add(cmbEliminarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 384, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-actualizar.png"))); // NOI18N
        jButton1.setText("Actualizar Datos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlEliminarPersonal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("paterno");
        pnlEliminarPersonal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 20));

        btnEliminarPersonal.setText("Eliminar Persona");
        btnEliminarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonalActionPerformed(evt);
            }
        });
        pnlEliminarPersonal.add(btnEliminarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("El personal registrado en el sistema puede consultarlo acontinuacion");
        pnlEliminarPersonal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        tblConsultaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Curp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblConsultaPersonal);

        pnlEliminarPersonal.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 520, 240));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Tome en cuenta que se muestra por nombre y apellido");
        pnlEliminarPersonal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarPnl.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlEliminarPersonal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        lblMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblMoverMouseDragged(evt);
            }
        });
        lblMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMoverMousePressed(evt);
            }
        });
        pnlEliminarPersonal.add(lblMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 70));

        lbljohasijd1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlEliminarPersonal.add(lbljohasijd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 610));

        getContentPane().add(pnlEliminarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonalActionPerformed
        try{
            if(cmbEliminarPersonal.getSelectedIndex()==0){
                showMessageDialog(this,"Por favor selecciona a un dato a eliminar");
            }else{
                int decision=showConfirmDialog(this,"¿Esta seguro que desea eliminar este dato?");
        if(decision==0){
            if(metodo.eliminarPersonal(cmbEliminarPersonal.getSelectedItem().toString())){
                javax.swing.JOptionPane.showMessageDialog(null, "Dato eliminado con exito");
                
               llenarPersonal();
            }
             }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_btnEliminarPersonalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int filas=modeloTabla.getRowCount();
            for(int i=0;filas>i;i++){
                modeloTabla.removeRow(0);
            }
            if(modeloTabla.getRowCount()==0){
                metodo.llenadoConsultaPersonalCurp(modeloTabla);
                showMessageDialog(this,"Datos Actualizados");
            }else{
                showMessageDialog(this,"No fue posible actualizar la tabla");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazEliminarPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMousePressed
          //para poder arrastar la ventana
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblMoverMousePressed

    private void lblMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMouseDragged
        //Para mover la ventana
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblMoverMouseDragged

    private void cmbEliminarPersonalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEliminarPersonalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEliminarPersonalItemStateChanged
   //LLENARA EL CMB con el personal disponible
    public void llenarPersonal(){
     try {
        ArrayList<String > personasDisponibles = metodo.extraerPersonal();
        cmbEliminarPersonal.removeAllItems();
        cmbEliminarPersonal.addItem("Seleccione a la persona");
        for(int i=0; i<personasDisponibles.size();i++){
        cmbEliminarPersonal.addItem(personasDisponibles.get(i));
          
                
        }
        
        } catch (SQLException ex) {
        Logger.getLogger(InterfazEliminarPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEliminarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPersonal;
    private javax.swing.JComboBox<String> cmbEliminarPersonal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lbljohasijd1;
    private javax.swing.JPanel pnlEliminarPersonal;
    private javax.swing.JTable tblConsultaPersonal;
    // End of variables declaration//GEN-END:variables
}
