/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MD.USUARIOSYPERMISOS.VISTAS;

import MD.PERSONAL.VISTAS.*;
import MDPERSONAL.CONTROLADORES.BDPERSONAL;
import MDPERSONAL.MODELOS.Personal;
import MDUSUARIOS.CONTROLADORES.BDUSUARIOS;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanramon
 */
public class InterfazEliminarUsuarios extends javax.swing.JFrame {

  //Avriables para poder mover la ventana
    int x=0;
    int y=0;
    BDPERSONAL metodo=new BDPERSONAL();
    DefaultTableModel modeloTablaUsuarios = new DefaultTableModel();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        BDUSUARIOS metodoU =new BDUSUARIOS();
    public InterfazEliminarUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        
        //cargara lso nombres de las personas registradas en el sistema en el cmb
      llenarUsuarios();
      
      /*CARGAR TABLA DE Usuarios*/
           modeloTablaUsuarios=(DefaultTableModel) tblUsuarios.getModel();
       try {
            for(int i=0;i<modeloTablaUsuarios.getRowCount();i++){
                modeloTablaUsuarios.removeRow(i);
            }
            metodoU.llenadoConsultaUsuarios(modeloTablaUsuarios);

        } catch (SQLException ex) {
             
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEliminarPersonal = new javax.swing.JPanel();
        cmbEliminarUsuario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMover = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lbljohasijd1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEliminarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        pnlEliminarPersonal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEliminarPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbEliminarUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el usuario" }));
        cmbEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbEliminarUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEliminarUsuarioItemStateChanged(evt);
            }
        });
        cmbEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEliminarUsuarioActionPerformed(evt);
            }
        });
        pnlEliminarPersonal.add(cmbEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 384, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-actualizar.png"))); // NOI18N
        jButton1.setText("Actualizar Datos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlEliminarPersonal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        btnEliminarUsuario.setText("Eliminar Usuario ");
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        pnlEliminarPersonal.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Los usuarios registrados actualmente se muestran en esta tabla");
        pnlEliminarPersonal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarPnl.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlEliminarPersonal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        lblMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblMoverMouseDragged(evt);
            }
        });
        lblMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMoverMousePressed(evt);
            }
        });
        pnlEliminarPersonal.add(lblMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 70));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre usuario", "Tipo de usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblUsuarios);

        pnlEliminarPersonal.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 490, 240));

        lbljohasijd1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlEliminarPersonal.add(lbljohasijd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 750, 610));

        getContentPane().add(pnlEliminarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        try{
            if(cmbEliminarUsuario.getSelectedIndex()==0){
                showMessageDialog(this,"Por favor selecciona el dato a eliminar");
            }else{
                int decision=showConfirmDialog(this,"¿Esta seguro que desea eliminar a este usuario?");
        if(decision==0){
            if(metodoU.eliminarUsuario(cmbEliminarUsuario.getSelectedItem().toString())){
                showMessageDialog(this,"Usuario eliminado con exito");
               llenarUsuarios();
               actualizarUsuarios();
            }
             }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarUsuarios();
    }//GEN-LAST:event_jButton1ActionPerformed
public void actualizarUsuarios(){
    try {
            int filas=modeloTablaUsuarios.getRowCount();
            for(int i=0;filas>i;i++){
                modeloTablaUsuarios.removeRow(0);
            }
            if(modeloTablaUsuarios.getRowCount()==0){
               metodoU.llenadoConsultaUsuarios(modeloTablaUsuarios);
                showMessageDialog(this,"Datos Actualizados");
            }else{
                showMessageDialog(this,"No fue posible actualizar los datos");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazEliminarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMousePressed
          //para poder arrastar la ventana
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblMoverMousePressed

    private void lblMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMouseDragged
        //Para mover la ventana
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblMoverMouseDragged

    private void cmbEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEliminarUsuarioActionPerformed

    private void cmbEliminarUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEliminarUsuarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEliminarUsuarioItemStateChanged
   //LLENARA EL CMB con el personal disponible
    public void llenarUsuarios(){
     try {
        ArrayList<String > usuariosDisponibles = metodoU.extraerUsuarios();
        cmbEliminarUsuario.removeAllItems();
        cmbEliminarUsuario.addItem("Seleccione el usuario");
        for(int i=0; i<usuariosDisponibles.size();i++){
        cmbEliminarUsuario.addItem(usuariosDisponibles.get(i));
          
                
        }
        
        } catch (SQLException ex) {
        Logger.getLogger(InterfazEliminarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEliminarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JComboBox<String> cmbEliminarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lbljohasijd1;
    private javax.swing.JPanel pnlEliminarPersonal;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
