/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MD.USUARIOSYPERMISOS.VISTAS;

import MDPERSONAL.MODELOS.Personal;
import MDPERSONAL.MODELOS.TipoUsuario;
import MDPERSONAL.MODELOS.Usuario;
import MDUSUARIOS.CONTROLADORES.BDUSUARIOS;
import java.awt.Font;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author juanramon
 */
public class InterfazRegistroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistroUsuarios
     */
    //INTANCIAS
    Validaciones valida=new Validaciones();
    FuncionesInterfazes funcion= new FuncionesInterfazes();
    BDUSUARIOS metodo=new BDUSUARIOS();
      int x=0;
     int y=0;
     
    public InterfazRegistroUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        
        p1.setVisible(false);
        p2.setVisible(false);
       lblContraseña.setVisible(false);
         //cargara lso nombres de las personas registradas en el sistema
        ArrayList<Personal> arrayPersona = BDUSUARIOS.selectPersonal();
        
        for(int i = 0; i < arrayPersona.size(); i++){
            this.cmbPersonal.addItem("NOMBRE: "+arrayPersona.get(i).getNom_per()+" | APELLIDO: "+arrayPersona.get(i).getApe_pat_per());
        }
        //cargar roles de usuario
                ArrayList<TipoUsuario> arrayTipoUsu = BDUSUARIOS.selectTipUsuario();
        for(int i = 0; i < arrayTipoUsu.size(); i++){
            
            this.cmbTipoUsu.addItem(arrayTipoUsu.get(i).getNom_tip());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbPersonal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarPass = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbTipoUsu = new javax.swing.JComboBox<>();
        p2 = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblInfoContraseña = new javax.swing.JLabel();
        cbVerificar = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la persona" }));
        cmbPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbPersonal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPersonalItemStateChanged(evt);
            }
        });
        cmbPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 410, -1));

        jLabel1.setText("Crear una cuenta para:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(lblCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 54, 159, 21));

        txtNombreUsuario.setEnabled(false);
        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 145, -1));

        jLabel2.setText("Nombre de Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 128, -1));

        btnGenerarPass.setText("Generar Contraseña");
        btnGenerarPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton2.setText("Registrar Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 24));

        jLabel3.setText("Tipo de Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        cmbTipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Rol", "Administrador de sistema", "Administrativo", "Almacenista", "Secretari@" }));
        cmbTipoUsu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoUsuItemStateChanged(evt);
            }
        });
        cmbTipoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoUsuActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTipoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 131, -1));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacionV.png"))); // NOI18N
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 26));

        lblContraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 130, 20));

        lblInfoContraseña.setText("La contraseña por defecto es:");
        jPanel1.add(lblInfoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 20));

        cbVerificar.setText("Lo he hecho");
        cbVerificar.setEnabled(false);
        cbVerificar.setOpaque(false);
        jPanel1.add(cbVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel5.setText("Si usted a tomado copia de su usuario ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel6.setText("y contraseña por favor verifique la casilla ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel7.setText("siguiente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 110));

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarPnl.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 30, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPersonalActionPerformed

    private void cmbPersonalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPersonalItemStateChanged
      if(cmbPersonal.getSelectedIndex()!=0){
          txtNombreUsuario.setEnabled(true);
      }
      
      
        if(lblContraseña.getText()!=null&&p1.isVisible()==false||p2.isVisible()==false||cmbPersonal.getSelectedIndex()==0){
            cbVerificar.setEnabled(false);
        }else{
        cbVerificar.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmbPersonalItemStateChanged

    private void txtNombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyPressed
        valida.validarNombreUsuario(txtNombreUsuario,p1);
       
        if(lblContraseña.getText()!=null&&p1.isVisible()==false||p2.isVisible()==false||cmbPersonal.getSelectedIndex()==0){
            cbVerificar.setEnabled(false);
        }else{
        cbVerificar.setEnabled(true);
            
        }
    }//GEN-LAST:event_txtNombreUsuarioKeyPressed

    private void txtNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyReleased
         valida.validarNombreUsuario(txtNombreUsuario,p1);
         
         //validar
        if(lblContraseña.getText()!=null&&p1.isVisible()==false||p2.isVisible()==false||cmbPersonal.getSelectedIndex()==0){
            cbVerificar.setEnabled(false);
        }else{
        cbVerificar.setEnabled(true);
            
        }
    }//GEN-LAST:event_txtNombreUsuarioKeyReleased

    private void cmbTipoUsuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoUsuItemStateChanged
      if(cmbTipoUsu.getSelectedIndex()!=0){
          p2.setVisible(true);
          
      }else if(cmbTipoUsu.getSelectedIndex()==0){
          p2.setVisible(false);
      }
      
      
      //validar
        if(lblContraseña.getText()!=null&&p1.isVisible()==false||p2.isVisible()==false||cmbPersonal.getSelectedIndex()==0){
            cbVerificar.setEnabled(false);
        }else{
        cbVerificar.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmbTipoUsuItemStateChanged

    private void btnGenerarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPassActionPerformed
   if(p1.isVisible()==true&&p2.isVisible()==true){
   String contraseña="";
   contraseña=funcion.creaPass();
   
   lblContraseña.setText(contraseña);
   lblContraseña.setVisible(true);
   cbVerificar.setEnabled(true);
   }else{
       showMessageDialog(null,"Por favor verifica los campos");
       
   }
    }//GEN-LAST:event_btnGenerarPassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(cbVerificar.isSelected()==true && lblContraseña.getText()!=null){
        int decision=showConfirmDialog(this,"¿Esta seguro que quiere desea registrar este usuario?");
         
        if(decision==0){
            Usuario usuario=new Usuario(txtNombreUsuario.getText(),lblContraseña.getText(),cmbPersonal.getSelectedIndex(),cmbTipoUsu.getSelectedIndex());
        if(metodo.insertUsuario(usuario)){showMessageDialog(this,"Usuario Registrado con Exito");}
         cmbPersonal.setSelectedIndex(0);
         txtNombreUsuario.setText("");
         txtNombreUsuario.setEnabled(false);
         p1.setVisible(false);
         cmbTipoUsu.setSelectedIndex(0);
         p2.setVisible(false);
        lblContraseña.setText("");
        lblContraseña.setVisible(false);
        cbVerificar.setEnabled(false);
        }
}else{
    showMessageDialog(this,"No se puede procesar por que:"+"\n"+"No ha seleccionado una persona,"+"\n"+"O un campo esta vacio,"+"\n"+"O El nombre de usuario no esta en mayusculas o no es mayor a 5 letras,"
            + ""+"\n"+"O no a seleccionado un rol,"+"\n"+"O no ha generado su contraseña,"+"\n"+"O no a verificado que ha guardado su contraseña y usuario");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbTipoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoUsuActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
  cmbPersonal.setSelectedIndex(0);
  txtNombreUsuario.setText("");
  txtNombreUsuario.setEnabled(false);
  p1.setVisible(false);
  cmbTipoUsu.setSelectedIndex(0);
  p2.setVisible(false);
  lblContraseña.setText("");
  lblContraseña.setVisible(false);
  cbVerificar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        //para poder arrastar la ventana
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
      //Para mover la ventana
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel8MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPass;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox cbVerificar;
    private javax.swing.JComboBox<String> cmbPersonal;
    private javax.swing.JComboBox<String> cmbTipoUsu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblInfoContraseña;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
